using AwesomeAssertions;
using ExampleProblems;
using ExampleProblems.CustomProblems;
using minuit2.net.Minimizers;
using minuit2.net.UnitTests.TestUtilities;
using static ExampleProblems.DerivativeConfiguration;
using static minuit2.net.MinimizationExitCondition;
using static minuit2.net.ParameterConfiguration;

namespace minuit2.net.UnitTests;

[TestFixture]
[Description("Absolute expectations are generated by iminuit, the Minuit2 wrapper for Python, for the same scenarios.")]
public class The_migrad_minimizer() : Any_gradient_based_minimizer(MigradMinimizer)
{
    private static readonly IMinimizer MigradMinimizer = Minimizer.Migrad;

    public class When_minimizing_a_least_squares_cost_function
    {
        [TestCase(WithoutDerivatives, 100)]
        [TestCase(WithGradient, 78)]
        public void yields_the_expected_result(
            DerivativeConfiguration derivativeConfiguration, 
            int expectedFunctionCalls)
        {
            var problem = new CubicPolynomialProblem(derivativeConfiguration: derivativeConfiguration);
            
            var result = MigradMinimizer.Minimize(problem);

            result.ShouldFulfill(x =>
            {
                x.Should().HaveNumberOfFunctionCallsCloseTo(expectedFunctionCalls);
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(12.49);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3");
                x.Variables.Should().Equal("c0", "c1", "c2", "c3");
                x.ParameterValues.Should().BeApproximately([9.974, -1.959, 0.9898, -0.09931]);
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 0.005623, -0.004301, 0.000881, -5.271e-05 },
                    { -0.004301, 0.004923, -0.001177, 7.655e-05 },
                    { 0.000881, -0.001177, 0.0003037, -2.067e-05 },
                    { -5.271e-05, 7.655e-05, -2.067e-05, 1.45e-06 }
                });
            });
        }

        [TestCase(WithoutDerivatives, 31)]
        [TestCase(WithGradient, 31)]
        public void with_fixed_parameters_yields_the_expected_result(
            DerivativeConfiguration derivativeConfiguration, 
            int expectedFunctionCalls)
        {
            var problem = new CubicPolynomialProblem(
                c1: Fixed("c1", -1.97), 
                c3: Fixed("c3", -0.11),
                derivativeConfiguration: derivativeConfiguration);

            var result = MigradMinimizer.Minimize(problem);
            
            result.ShouldFulfill(x =>
            {
                x.Should().HaveNumberOfFunctionCallsCloseTo(expectedFunctionCalls);
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(437.7);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3");
                x.Variables.Should().Equal("c0", "c2");
                x.ParameterValues.Should().BeApproximately([9.411, -1.97, 1.088, -0.11]);
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 0.001092, 0.0, -1.918e-05, 0.0 },
                    { 0.0, 0.0, 0.0, 0.0 },
                    { -1.918e-05, 0.0, 6.211e-07, 0.0 },
                    { 0.0, 0.0, 0.0, 0.0 }
                });
            });
        }
        
        [Test]
        public void with_limited_parameters_yields_the_expected_result()
        {
            var problem = new CubicPolynomialProblem(
                c0: Variable("c0", 10.75, lowerLimit: 10.5),  // optimum is 10
                c3: Variable("c3", -0.11, upperLimit: -0.105));  // optimum is -0.1
            
            var result = MigradMinimizer.Minimize(problem);
            
            result.ShouldFulfill(x =>
            {
                x.Should().HaveNumberOfFunctionCallsCloseTo(444);
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(62.34);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3");
                x.Variables.Should().Equal("c0", "c1", "c2", "c3");
                x.ParameterValues.Should().BeApproximately([10.5, -2.39, 1.082, -0.105]);
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 7.023e-09, -3.654e-09, 3.124e-10, -1.261e-14 },
                    { -3.654e-09, 0.0002602, -3.344e-05, 5.468e-09 },
                    { 3.124e-10, -3.344e-05, 4.594e-06, -1.873e-09 },
                    { -1.261e-14, 5.468e-09, -1.873e-09, 1.211e-10 }
                });
            });
        }
        
        [Test]
        public void with_an_analytical_gradient_and_with_limited_parameters_yields_the_expected_result()
        {
            var problem = new CubicPolynomialProblem(
                c0: Variable("c0", 10.75, lowerLimit: 10.5),  // optimum is 10
                c3: Variable("c3", -0.11, upperLimit: -0.105),  // optimum is -0.1
                derivativeConfiguration: WithGradient);  

            var result = MigradMinimizer.Minimize(problem);

            // Covariances are slightly different from the numerical-gradient case (above).
            // This is because, in contrast to proper convergence, in the case of early termination at parameter limits,
            // the assumption of local quadratic behavior (parabolic approximation) around the terminal cost value is
            // generally not fulfilled. Therefore, covariances are not fully robust.
            result.ShouldFulfill(x =>
            {
                x.Should().HaveNumberOfFunctionCallsCloseTo(156);
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(62.34);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3");
                x.Variables.Should().Equal("c0", "c1", "c2", "c3");
                x.ParameterValues.Should().BeApproximately([10.5, -2.39, 1.082, -0.105]);
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 5.482e-09, -2.933e-09, 2.507e-10, -7.976e-15 },
                    { -2.933e-09, 0.0002602, -3.343e-05, 4.309e-09 },
                    { 2.507e-10, -3.343e-05, 4.589e-06, -1.476e-09 },
                    { -7.976e-15, 4.309e-09, -1.476e-09, 9.18e-11 }
                });
            });
        }
        
        [Test]
        public void with_unknown_data_errors_yields_the_expected_result(
            [Values] DerivativeConfiguration derivativeConfiguration)
        {
            var problem = new CubicPolynomialProblem(hasYErrors: false, derivativeConfiguration: derivativeConfiguration);
            
            var result = MigradMinimizer.Minimize(problem);
            
            result.ShouldFulfill(x =>
            {
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(0.1249);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3"); 
                x.Variables.Should().Equal("c0", "c1", "c2", "c3");
                x.ParameterValues.Should().BeApproximately([9.974, -1.959, 0.9898, -0.09931]); 
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 0.5623, -0.4301, 0.08809, -0.00527 },
                    { -0.4301, 0.4922, -0.1177, 0.007654 },
                    { 0.08809, -0.1177, 0.03036, -0.002067 },
                    { -0.00527, 0.007654, -0.002067, 0.000145 }
                });
            });
        }
        
        [Test]
        [Description("Assuming the initial minimization yields an ideal result — meaning the fitted model accurately " +
                     "describes the data apart from the superimposed noise — we recalculate the parameter " +
                     "uncertainties using the corresponding reduced chi-squared value for the error definition. " +
                     "Under this assumption, the resulting uncertainties are equivalent to those obtained by " +
                     "minimizing the cost function with correctly specified y-errors (i.e., the true standard " +
                     "deviation of the noise affecting the data).")]
        public void with_unknown_data_errors_and_subsequently_applying_error_definition_recalculation_followed_by_error_refinement_yields_the_expected_result(
            [Values] DerivativeConfiguration derivativeConfiguration)
        {
            var problem = new CubicPolynomialProblem(hasYErrors: false, derivativeConfiguration: derivativeConfiguration);
            
            var result = MigradMinimizer.MinimizeAndRefineErrors(problem);
            
            result.ShouldFulfill(x =>
            {
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(0.1249);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3");
                x.Variables.Should().Equal("c0", "c1", "c2", "c3");
                x.ParameterValues.Should().BeApproximately([9.974, -1.959, 0.9898, -0.09931]);
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 0.004391, -0.003358, 0.0006878, -4.115e-05 },
                    { -0.003358, 0.003843, -0.0009193, 5.977e-05 },
                    { 0.0006878, -0.0009193, 0.0002371, -1.614e-05 },
                    { -4.115e-05, 5.977e-05, -1.614e-05, 1.132e-06 }
                });
            });
        }
        
        [Test]
        [Description("This is a concrete example where the minimizer exits the valid parameter space by assigning a " +
                     "negative value to a bell curve's variance, causing a NaN in the cost value. The issue can be " +
                     "avoided by enforcing a lower bound of zero. If omitted, we still return the final minimization " +
                     "state with clear error details.")]
        public void leaving_the_valid_parameter_space_during_the_minimization_process_yields_an_invalid_result_with_non_finite_value_exit_condition_and_undefined_covariances_representing_the_last_state_of_the_process()
        {
            var problem = new BellCurveProblem(
                location: Variable("loc", 6.41),
                variance: Variable("var", 1.42)
            );
            var minimizerConfiguration = new MinimizerConfiguration(Strategy.Rigorous);

            var result = MigradMinimizer.Minimize(problem, minimizerConfiguration);

            result.ShouldFulfill(x =>
            {
                x.IsValid.Should().BeFalse();
                x.ExitCondition.Should().Be(NonFiniteValue);
                x.NumberOfFunctionCalls.Should().BeGreaterThan(0);
                x.ParameterCovarianceMatrix.Should().BeNull();
                x.CostValue.Should().Be(problem.Cost.ValueFor(x.ParameterValues)).And.NotBeFinite();
            });
        }
    }

    public class When_minimizing_a_sum_of_least_squares_cost_functions
    {
        [Test]
        [Description("Ensures that recalculation of the error definition for least squares cost functions with " +
                     "unknown y-errors and, hence, parameter covariances works (on a per-cost basis).")]
        public void not_sharing_any_parameters_where_some_have_unknown_data_errors_and_subsequently_applying_error_refinement_yields_a_result_equivalent_to_the_results_for_the_isolated_components(
                [Values] DerivativeConfiguration derivativeConfiguration, 
                [Values] Strategy strategy)
        {
            var problem1 = new CubicPolynomialProblem(derivativeConfiguration: derivativeConfiguration);
            var problem2 = new CubicPolynomialProblem(
                c0: Variable("c0_2", 10.5),
                c1: Variable("c1_2", -2.5),
                c2: Variable("c2_2", 1.5),
                c3: Variable("c3_2", -0.15),
                hasYErrors: false,
                derivativeConfiguration: derivativeConfiguration);
            var sumProblem = problem1.SumWith(problem2);
            var minimizerConfiguration = new MaximumAccuracyMinimizerConfiguration(strategy);
            
            var component1Result = MigradMinimizer.MinimizeAndRefineErrors(problem1, minimizerConfiguration);
            var component2Result = MigradMinimizer.MinimizeAndRefineErrors(problem2, minimizerConfiguration);
            var sumResult = MigradMinimizer.MinimizeAndRefineErrors(sumProblem, minimizerConfiguration);

            sumResult.ShouldFulfill(x =>
            {
                x.CostValue.Should().BeApproximately(component1Result.CostValue + component2Result.CostValue);
                x.ParameterValues.Should().BeApproximately(component1Result.ParameterValues.Concat(component2Result.ParameterValues));
                x.ParameterCovarianceMatrix.Should()
                    .BeApproximately(component1Result.ParameterCovarianceMatrix.BlockConcat(component2Result.ParameterCovarianceMatrix), 
                        relativeTolerance: 0.004);
            });
        }

        [TestCase(WithoutDerivatives, WithoutDerivatives, 182)]
        [TestCase(WithGradient, WithoutDerivatives, 182)]
        [TestCase(WithGradient, WithGradient, 120)]
        public void with_defined_data_uncertainties_yields_the_expected_result(
            DerivativeConfiguration derivativeConfiguration1, 
            DerivativeConfiguration derivativeConfiguration2, 
            int expectedFunctionCalls)
        {
            var problem1 = new CubicPolynomialProblem(derivativeConfiguration: derivativeConfiguration1);
            var problem2 = new CubicPolynomialProblem(
                c1: Variable("c1_2", -2.1),
                c3: Variable("c3_2", -0.15),
                derivativeConfiguration: derivativeConfiguration2);
            var sumProblem = problem1.SumWith(problem2);

            var result = MigradMinimizer.Minimize(sumProblem);
            
            result.ShouldFulfill(x =>
            {
                x.Should().HaveNumberOfFunctionCallsCloseTo(expectedFunctionCalls);
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(24.99);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3", "c1_2", "c3_2");
                x.Variables.Should().Equal("c0", "c1", "c2", "c3", "c1_2", "c3_2");
                x.ParameterValues.Should().BeApproximately([9.974, -1.959, 0.9898, -0.09931, -1.959, -0.09931]);
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 0.002811, -0.00215, 0.0004404, -2.635e-05, -0.00215, -2.635e-05 },
                    { -0.00215, 0.002512, -0.0005887, 3.752e-05, 0.00241, 3.902e-05 },
                    { 0.0004404, -0.0005887, 0.0001518, -1.033e-05, -0.0005887, -1.033e-05 },
                    { -2.635e-05, 3.752e-05, -1.033e-05, 7.383e-07, 3.902e-05, 7.12e-07 },
                    { -0.00215, 0.00241, -0.0005887, 3.902e-05, 0.002512, 3.752e-05 },
                    { -2.635e-05, 3.902e-05, -1.033e-05, 7.12e-07, 3.752e-05, 7.384e-07 }
                });
            });
        }
        
        [Test]
        public void with_some_having_unknown_data_errors_yields_the_expected_result(
            [Values] DerivativeConfiguration derivativeConfiguration1, 
            [Values] DerivativeConfiguration derivativeConfiguration2)
        {
            var problem1 = new CubicPolynomialProblem(derivativeConfiguration: derivativeConfiguration1);
            var problem2 = new CubicPolynomialProblem(derivativeConfiguration: derivativeConfiguration2, hasYErrors: false);
            var sumProblem = problem1.SumWith(problem2);

            var result = MigradMinimizer.Minimize(sumProblem);
            
            result.ShouldFulfill(x =>
            {
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(12.62);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3");
                x.Variables.Should().Equal("c0", "c1", "c2", "c3");
                x.ParameterValues.Should().BeApproximately([9.974, -1.959, 0.9898, -0.09931]);
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 0.005567, -0.004258, 0.0008721, -5.218e-05 },
                    { -0.004258, 0.004873, -0.001166, 7.578e-05 },
                    { 0.0008721, -0.001166, 0.0003006, -2.046e-05 },
                    { -5.218e-05, 7.578e-05, -2.046e-05, 1.436e-06 }
                });
            });
        }

        [Test]
        [Description("Ensures parameter covariances are adjusted only for (inner) cost functions with unknown y-errors.")]
        public void with_some_having_unknown_data_errors_and_subsequently_applying_error_refinement_yields_the_expected_result(
            [Values] DerivativeConfiguration derivativeConfiguration1,  
            [Values] DerivativeConfiguration derivativeConfiguration2)
        {
            var problem1 = new CubicPolynomialProblem(derivativeConfiguration: derivativeConfiguration1);
            var problem2 = new CubicPolynomialProblem(derivativeConfiguration: derivativeConfiguration2, hasYErrors: false);
            var sumProblem = problem1.SumWith(problem2);

            var result = MigradMinimizer.MinimizeAndRefineErrors(sumProblem);
            
            result.ShouldFulfill(x =>
            {
                x.ExitCondition.Should().Be(Converged);
                x.IsValid.Should().BeTrue();
                x.CostValue.Should().BeApproximately(12.62);
                x.Parameters.Should().Equal("c0", "c1", "c2", "c3");
                x.Variables.Should().Equal("c0", "c1", "c2", "c3");
                x.ParameterValues.Should().BeApproximately([9.974, -1.959, 0.9898, -0.09931]);
                x.ParameterCovarianceMatrix.Should().BeApproximately(new[,]
                {
                    { 0.002465, -0.001886, 0.0003862, -2.311e-05 },
                    { -0.001886, 0.002158, -0.0005162, 3.356e-05 },
                    { 0.0003862, -0.0005162, 0.0001331, -9.062e-06 },
                    { -2.311e-05, 3.356e-05, -9.062e-06, 6.359e-07 }
                });
            });
        }
    }
}