name: Build and Pack Workflow

on:
  workflow_call:
    inputs:
      use-openmp:
        required: true
        type: string
      package-id:
        required: true
        type: string
      sem-ver:
        required: true
        type: string
      assembly-sem-ver:
        required: true
        type: string
      assembly-sem-file-ver:
        required: true
        type: string
      assembly-informational-version:
        required: true
        type: string

jobs:
  build-native:
    name: Build native libraries for ${{ matrix.rid }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - rid: win-x86
            runner: windows-2025
          - rid: win-x64
            runner: windows-2025
          - rid: win-arm64
            runner: windows-11-arm
          - rid: osx-arm64
            runner: macos-15
          - rid: osx-x64
            runner: macos-15-intel
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install SWIG (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew install swig
          if [ "${{ inputs.use-openmp }}" == "ON" ]; then
            brew install libomp
          fi

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5

      - name: Build
        shell: pwsh
        run: |
          dotnet build ./minuit2.net/minuit2.net.csproj `
            --runtime ${{ matrix.rid }} `
            --configuration Release `
            -p:UseOpenMP=${{ inputs.use-openmp }} `
            --no-self-contained

      - name: Test
        if: matrix.rid != 'win-x86'
        shell: pwsh
        run: |
          dotnet test ./test/minuit2.net.UnitTests/minuit2.net.UnitTests.csproj `
            --runtime ${{ matrix.rid }} `
            --configuration Release `
            -p:UseOpenMP=${{ inputs.use-openmp }}

      - name: Upload Runtime Binaries
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.rid }}-runtime-${{ inputs.package-id }}
          path: ./minuit2.net/runtimes/
          if-no-files-found: error

  build-managed:
    name: Build managed .NET library
    runs-on: windows-2025
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5

      - name: Build
        shell: pwsh
        run: |
          dotnet build ./minuit2.net/minuit2.net.csproj `
            -p:Version=${{ inputs.sem-ver }} `
            -p:FileVersion=${{ inputs.assembly-sem-file-ver }} `
            -p:AssemblyVersion=${{ inputs.assembly-sem-ver }} `
            -p:AssemblyInformationalVersion=${{ inputs.assembly-informational-version }} `
            --configuration Release `
            -p:UseOpenMP=${{ inputs.use-openmp }} `
            --no-self-contained

      - name: Upload ROOT License
        uses: actions/upload-artifact@v7
        with:
          name: root-license-${{ inputs.package-id }}
          path: ./minuit2.net/root-license/
          if-no-files-found: error

      - name: Upload C# Assembly
        uses: actions/upload-artifact@v7
        with:
          name: csharp-assembly-${{ inputs.package-id }}
          path: ./minuit2.net/bin/Release/net8.0/${{ inputs.package-id }}.dll
          if-no-files-found: error

  package:
    name: Create NuGet Package
    needs: [ build-native, build-managed ]
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5

      - name: Download C# Assembly
        uses: actions/download-artifact@v8
        with:
          name: csharp-assembly-${{ inputs.package-id }}
          path: ./minuit2.net/bin/Release/net8.0/

      - name: Download ROOT License
        uses: actions/download-artifact@v8
        with:
          name: root-license-${{ inputs.package-id }}
          path: ./minuit2.net/root-license/

      - name: Download Runtime Binaries
        uses: actions/download-artifact@v8
        with:
          pattern: "*-runtime-${{ inputs.package-id }}"
          path: ./minuit2.net/runtimes/
          merge-multiple: true

      - name: Verify Runtime Binaries
        shell: pwsh
        run: |
          $requiredRids = @("win-x86", "win-x64", "win-arm64", "osx-x64", "osx-arm64")
          foreach ($rid in $requiredRids) {
            if (-not (Test-Path "./minuit2.net/runtimes/$rid")) {
              Write-Error "Cannot package: Missing runtime binaries for RID: $rid"
              exit 1
            }
          }

      - name: Restore Dependencies
        run: dotnet restore ./minuit2.net/minuit2.net.csproj

      - name: Create NuGet
        shell: pwsh
        run: |
          dotnet pack `
            -p:Version=${{ inputs.sem-ver }} `
            -p:FileVersion=${{ inputs.assembly-sem-file-ver }} `
            -p:AssemblyVersion=${{ inputs.assembly-sem-ver }} `
            -p:AssemblyInformationalVersion=${{ inputs.assembly-informational-version }} `
            -p:PackageId=${{ inputs.package-id }} `
            -p:UseOpenMP=${{ inputs.use-openmp }} `
            --no-build `
            --configuration Release `
            --output ./bin `
            --warnaserror `
            --nologo `
            ./minuit2.net/minuit2.net.csproj

      - name: Install dotnet-validate
        run: dotnet tool install --global dotnet-validate --version 0.0.1-preview.537

      - name: Validate NuGet
        run: dotnet-validate package local "./bin/*.nupkg"

      - name: Upload NuGet
        uses: actions/upload-artifact@v7
        with:
          name: nuget-package-${{ inputs.package-id }}
          path: ./bin/
          if-no-files-found: error
