name: Minuit2.NET CI/CD Pipeline
run-name: >
  ${{ github.event_name }} ·
  ${{ github.head_ref || github.ref_name }} ·
  ${{ github.event.head_commit && github.event.head_commit.message || github.sha }}

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ '**' ]

jobs:
  determine-version:
    name: Determine Version
    runs-on: ubuntu-latest
    outputs:
      sem-ver: ${{ steps.determine-version.outputs.GitVersion_SemVer }}
      assembly-sem-ver: ${{ steps.determine-version.outputs.GitVersion_AssemblySemVer }}
      assembly-sem-file-ver: ${{ steps.determine-version.outputs.GitVersion_AssemblySemFileVer }}
      assembly-informational-version: ${{ steps.determine-version.outputs.GitVersion_InformationalVersion }}
      pre-release-label: ${{ steps.determine-version.outputs.PreReleaseLabel }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4

      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Determine Version
        id: determine-version
        uses: gittools/actions/gitversion/execute@v4
        with:
          configFilePath: GitVersion.yml

  standard-branch:
    name: Standard
    uses: ./.github/workflows/build-and-pack.yml
    needs: [ determine-version ]
    with:
      use-openmp: 'OFF'
      package-id: 'minuit2.net'
      sem-ver: ${{ needs.determine-version.outputs.sem-ver }}
      assembly-sem-ver: ${{ needs.determine-version.outputs.assembly-sem-ver }}
      assembly-sem-file-ver: ${{ needs.determine-version.outputs.assembly-sem-file-ver }}
      assembly-informational-version: ${{ needs.determine-version.outputs.assembly-informational-version }}

  openmp-branch:
    name: OpenMP
    uses: ./.github/workflows/build-and-pack.yml
    needs: [ determine-version ]
    with:
      use-openmp: 'ON'
      package-id: 'minuit2.net.openmp'
      sem-ver: ${{ needs.determine-version.outputs.sem-ver }}
      assembly-sem-ver: ${{ needs.determine-version.outputs.assembly-sem-ver }}
      assembly-sem-file-ver: ${{ needs.determine-version.outputs.assembly-sem-file-ver }}
      assembly-informational-version: ${{ needs.determine-version.outputs.assembly-informational-version }}

  publish:
    name: Publish NuGet Packages
    needs: [ standard-branch, openmp-branch ]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Download NuGet
        uses: actions/download-artifact@v8
        with:
          pattern: "nuget-package-*"
          path: ./bin/
          merge-multiple: true

      - name: Publish NuGet
        run: |
          dotnet nuget push "./bin/*.nupkg" --api-key ${{ secrets.PUBLISH_PACKAGE_TOKEN }} --source "https://api.nuget.org/v3/index.json"

  release:
    name: Create GitHub Release
    needs: [ publish, determine-version ]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      packages: write
      contents: write
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: "${{ needs.determine-version.outputs.sem-ver }}"
          prerelease: ${{ needs.determine-version.outputs.pre-release-label != '' }}
